export const staticPrimaryColor = "#5D5FEF";
export const staticPrimaryDarkenColor = "#5456D9";
export const themes = {
  light: {
    dark: false,
    colors: {
      primary: staticPrimaryColor,
      "on-primary": "#fff",
      "primary-darken-1": staticPrimaryDarkenColor,
      secondary: "#7C7F84", // Slightly darkened
      "secondary-darken-1": "#6F7277",
      "on-secondary": "#fff",
      success: "#10B981",
      "success-darken-1": "#46A500",
      "on-success": "#fff",
      info: "#149FE6", // Slight adjustment
      "info-darken-1": "#128DCF",
      "on-info": "#fff",
      warning: "#E6A200",
      "warning-darken-1": "#CC8F00",
      "on-warning": "#fff",
      error: "#EF4444",
      "error-darken-1": "#CC3B40",
      "on-error": "#fff",
      background: "#f4f5fa",
      "on-background": "#2E263D",
      surface: "#fff",
      "on-surface": "#2E263D",
      "grey-50": "#F9F9F9",
      "grey-100": "#F2F2F2",
      "grey-200": "#E9E9E9",
      "grey-300": "#D0D0D0",
      "grey-400": "#B4B4B4",
      "grey-500": "#939393",
      "grey-600": "#737373",
      "grey-700": "#606060",
      "grey-800": "#444444",
      "grey-900": "#262626",
      "perfect-scrollbar-thumb": "#CBCBCB",
      "skin-bordered-background": "#fff",
      "skin-bordered-surface": "#fff",
      "expansion-panel-text-custom-bg": "#fafafa",
      "track-bg": "#F0F2F8",
      "chat-bg": "#F7F6FA",
      "button-bg-primary": "#EA4475",
      "button-bg-disabled": "#B3B9CF",
      "text-color-primary": "#fff",
      "text-color-secondary": "#374151",
      "text-color-gray": "#1B202D",
      "input-border-radius": "10px",
      "button-border-radius": "100px",
      "chat-message-bg-primary": staticPrimaryColor,
      "chat-message-bg-secondary": "#F2F4FB",
    },
    variables: {
      "code-color": "#AF00FF", // Adjusted slightly to be in harmony with primary
      "overlay-scrim-background": "#2E263D",
      "tooltip-background": "#1A0E33",
      "overlay-scrim-opacity": 0.5,
      "hover-opacity": 0.04,
      "focus-opacity": 0.1,
      "selected-opacity": 0.08,
      "activated-opacity": 0.16,
      "pressed-opacity": 0.14,
      "dragged-opacity": 0.1,
      "disabled-opacity": 0.4,
      "border-color": "#2E263D",
      "border-opacity": 0.12,
      "table-header-color": "#F6F7FB",
      "high-emphasis-opacity": 0.9,
      "medium-emphasis-opacity": 0.7,

      // 👉 shadows
      "shadow-key-umbra-color": "#2E263D",
      "shadow-xs-opacity": "0.16",
      "shadow-sm-opacity": "0.18",
      "shadow-md-opacity": "0.20",
      "shadow-lg-opacity": "0.22",
      "shadow-xl-opacity": "0.24",
    },
  },
  dark: {
    dark: false,
    colors: {
      primary: staticPrimaryColor,
      "on-primary": "#fff",
      "primary-darken-1": staticPrimaryDarkenColor,
      secondary: "#7C7F84", // Slightly darkened
      "secondary-darken-1": "#6F7277",
      "on-secondary": "#fff",
      success: "#4DB600",
      "success-darken-1": "#46A500",
      "on-success": "#fff",
      info: "#149FE6", // Slight adjustment
      "info-darken-1": "#128DCF",
      "on-info": "#fff",
      warning: "#E6A200",
      "warning-darken-1": "#CC8F00",
      "on-warning": "#fff",
      error: "#E64449",
      "error-darken-1": "#CC3B40",
      "on-error": "#fff",
      background: "#f4f5fa",
      "on-background": "#2E263D",
      surface: "#fff",
      "on-surface": "#2E263D",
      "grey-50": "#F9F9F9",
      "grey-100": "#F2F2F2",
      "grey-200": "#E9E9E9",
      "grey-300": "#D0D0D0",
      "grey-400": "#B4B4B4",
      "grey-500": "#939393",
      "grey-600": "#737373",
      "grey-700": "#606060",
      "grey-800": "#444444",
      "grey-900": "#262626",
      "perfect-scrollbar-thumb": "#CBCBCB",
      "skin-bordered-background": "#fff",
      "skin-bordered-surface": "#fff",
      "expansion-panel-text-custom-bg": "#fafafa",
      "track-bg": "#F0F2F8",
      "chat-bg": "#F7F6FA",
      "button-bg-primary": "#EA4475",
      "button-bg-disabled": "#B3B9CF",
      "text-color-primary": "#fff",
      "text-color-secondary": "#374151",
      "text-color-gray": "#1B202D",
      "input-border-radius": "10px",
      "button-border-radius": "100px",
      "chat-message-bg-primary": staticPrimaryColor,
      "chat-message-bg-secondary": "#F2F4FB",
    },
    variables: {
      "code-color": "#AF00FF", // Adjusted slightly to be in harmony with primary
      "overlay-scrim-background": "#2E263D",
      "tooltip-background": "#1A0E33",
      "overlay-scrim-opacity": 0.5,
      "hover-opacity": 0.04,
      "focus-opacity": 0.1,
      "selected-opacity": 0.08,
      "activated-opacity": 0.16,
      "pressed-opacity": 0.14,
      "dragged-opacity": 0.1,
      "disabled-opacity": 0.4,
      "border-color": "#2E263D",
      "border-opacity": 0.12,
      "table-header-color": "#F6F7FB",
      "high-emphasis-opacity": 0.9,
      "medium-emphasis-opacity": 0.7,

      // 👉 shadows
      "shadow-key-umbra-color": "#2E263D",
      "shadow-xs-opacity": "0.16",
      "shadow-sm-opacity": "0.18",
      "shadow-md-opacity": "0.20",
      "shadow-lg-opacity": "0.22",
      "shadow-xl-opacity": "0.24",
    },
  },
};
export default themes;
